"use client"

import { useMemo, useState } from "react"
import {
  Activity, AlertCircle, ArrowUpRight, BookOpen, Bot, BrainCircuit, Check, ChevronDown, CircleHelp,
  Code2, Command, Copy, FileCode2, Gauge, KeyRound, LifeBuoy, Menu, MessageSquare, MoreHorizontal,
  PanelLeft, Play, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Timer, Trash2,
  TrendingUp, Upload, UserRound, X, Zap
} from "lucide-react"
import "./styles.css"

type View = "Chat" | "Playground" | "API" | "Models" | "Docs" | "Usage" | "API Health" | "Settings"

const navGroups = [
  { label: "BUILD", items: [{ name: "Chat", icon: MessageSquare }, { name: "Playground", icon: Terminal }] },
  { label: "DEVELOP", items: [{ name: "API", icon: Code2 }, { name: "Models", icon: BrainCircuit }, { name: "Docs", icon: BookOpen }] },
  { label: "MONITOR", items: [{ name: "Usage", icon: TrendingUp }, { name: "API Health", icon: Activity }] },
  { label: "SYSTEM", items: [{ name: "Settings", icon: Settings }] },
]

const models = [
  { name: "Veyra Core 70B", id: "veyra-core-70b", type: "Chat", context: "128K", status: "Available", speed: "Fast" },
  { name: "Veyra Swift 8B", id: "veyra-swift-8b", type: "Chat", context: "32K", status: "Available", speed: "Very fast" },
  { name: "Veyra Reason 32B", id: "veyra-reason-32b", type: "Reasoning", context: "64K", status: "Available", speed: "Balanced" },
  { name: "Veyra Vision", id: "veyra-vision-11b", type: "Multimodal", context: "32K", status: "Beta", speed: "Fast" },
]

export default function Home() {
  const [view, setView] = useState<View>("Chat")
  const [dark, setDark] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [commandOpen, setCommandOpen] = useState(false)

  const renderView = () => {
    if (view === "Chat") return <ChatView />
    if (view === "Playground") return <PlaygroundView />
    if (view === "API") return <ApiView />
    if (view === "Models") return <ModelsView />
    if (view === "Docs") return <DocsView2 />
    if (view === "Usage") return <UsageView />
    if (view === "API Health") return <HealthView />
    return <SettingsView />
  }

  return <main className={dark ? "app dark" : "app"}>
    <aside className={sidebarOpen ? "sidebar" : "sidebar collapsed"}>
      <div className="brand"><div className="brand-mark">V</div>{sidebarOpen && <><span>VEYRA</span><span className="brand-tag">DEV</span></>}</div>
      {sidebarOpen && <div className="workspace"><div className="workspace-icon">A</div><div><strong>Acme workspace</strong><span>Developer plan</span></div><ChevronDown size={14}/></div>}
      <nav>
        {navGroups.map(group => <div className="nav-group" key={group.label}>{sidebarOpen && <div className="nav-label">{group.label}</div>}{group.items.map(item => { const Icon = item.icon; return <button key={item.name} className={view === item.name ? "nav-item active" : "nav-item"} onClick={() => setView(item.name as View)} title={item.name}><Icon size={16}/>{sidebarOpen && <span>{item.name}</span>}{item.name === "API" && sidebarOpen && <span className="new-dot"/>}</button>})}</div>)}
      </nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => setView("Docs")}><CircleHelp size={16}/>{sidebarOpen && <span>Help center</span>}</button><div className="profile"><div className="avatar">JD</div>{sidebarOpen && <div><strong>Jordan Davis</strong><span>jordan@acme.co</span></div>}</div></div>
    </aside>
    <section className="content">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setSidebarOpen(!sidebarOpen)}><Menu size={18}/></button><div className="crumb"><span>Workspace</span><span className="slash">/</span><strong>{view}</strong></div><div className="top-actions"><button className="top-link" onClick={() => setView("Docs")}><BookOpen size={15}/> Docs</button><span className="status"><i/> All systems operational</span><button className="command-trigger" onClick={() => setCommandOpen(true)}><Search size={15}/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Zap size={17}/> : <div className="sun">☼</div>}</button></div></header>
      <div className="page">{renderView()}</div>
    </section>
    {commandOpen && <CommandPalette close={() => setCommandOpen(false)} navigate={(v) => {setView(v); setCommandOpen(false)}}/>}
  </main>
}

function PageHeader({ eyebrow, title, description, action }: {eyebrow?: string, title: string, description: string, action?: React.ReactNode}) { return <div className="page-header">{eyebrow && <div className="eyebrow">{eyebrow}</div>}<div className="header-row"><div><h1>{title}</h1><p>{description}</p></div>{action}</div></div> }
function Card({ children, className = "" }: {children: React.ReactNode, className?: string}) { return <div className={`card ${className}`}>{children}</div> }
function Status({ children, tone = "green" }: {children: React.ReactNode, tone?: string}) { return <span className={`status-badge ${tone}`}><i/>{children}</span> }
function CopyButton({ text = "Copy" }: {text?: string}) { const [copied, setCopied] = useState(false); return <button className="copy-button" onClick={() => {setCopied(true); setTimeout(() => setCopied(false), 1200)}}>{copied ? <Check size={13}/> : <Copy size={13}/>} {copied ? "Copied" : text}</button> }

function ChatView() { const [message, setMessage] = useState(""); const [messages, setMessages] = useState<string[]>([]); const send = () => { const trimmed = message.trim(); if (!trimmed) return; setMessages(current => [...current, trimmed]); setMessage(""); }; return <><PageHeader eyebrow="BUILD / CHAT" title="Chat" description="Test models and explore responses in a focused workspace." action={<button className="button secondary" onClick={() => {setMessages([]); setMessage("")}}><Trash2 size={16}/> Clear</button>}/><div className="chat-shell"><div className="conversation-head"><div className="model-chip"><div className="model-glyph"><Bot size={15}/></div><div><strong>Veyra Core 70B</strong><span>veyra-core-70b</span></div><ChevronDown size={14}/></div><div className="conversation-actions"><span className="soft-label">{messages.length ? `${messages.length} messages` : "Unsaved conversation"}</span><button className="icon-button"><SlidersHorizontal size={16}/></button></div></div><div className="messages">{messages.length === 0 ? <div className="empty-chat"><div className="empty-mark"><Sparkles size={22}/></div><h2>What are you building?</h2><p>Start a conversation with Veyra. Ask a question, generate code, or explore an idea.</p><div className="prompt-suggestions"><button onClick={() => setMessage("Explain how streaming works in the Veyra API")}>Explain streaming in the API <ArrowUpRight size={14}/></button><button onClick={() => setMessage("Write a TypeScript function to summarize text")}>Write a TypeScript function <ArrowUpRight size={14}/></button></div></div> : <div className="message-list">{messages.map((item, index) => <div className="chat-message" key={`${item}-${index}`}><span className="avatar">JD</span><p>{item}</p></div>)}</div>}</div><div className="composer"><textarea value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => {if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) {e.preventDefault(); send()}}} placeholder="Message Veyra..."/><div className="composer-footer"><div className="composer-tools"><button className="tool-button"><Plus size={16}/></button><span>Core 70B</span><span className="separator-dot"/><span>128K context</span></div><div className="composer-meta"><kbd>Enter</kbd><span>to send</span><button className="send-button" aria-label="Send" onClick={send}><ArrowUpRight size={17}/></button></div></div></div></div></> }

function PlaygroundView() { const [tab, setTab] = useState("Request"); const [ran, setRan] = useState(false); return <><PageHeader eyebrow="BUILD / PLAYGROUND" title="Playground" description="Make requests, inspect responses, and generate production-ready code." action={<button className="button primary" onClick={() => {setRan(true); setTab("Response")}}><Play size={15}/> {ran ? "Run again" : "Run request"}</button>}/><div className="play-toolbar"><div className="method">POST</div><div className="endpoint"><span>https://api.veyra.ai</span>/v1/chat/completions</div><div className="toolbar-model"><Bot size={14}/> veyra-core-70b <ChevronDown size={13}/></div><span className="toolbar-spacer"/><button className="icon-button"><Settings size={16}/></button></div><div className="playground-grid"><Card className="panel"><div className="panel-tabs">{["Request", "Response", "Code"].map(t => <button key={t} className={tab === t ? "tab active" : "tab"} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === "Request" ? <div className="request-body"><label>Messages</label><div className="message-editor"><div className="editor-role"><span className="role-dot user"/> user <ChevronDown size={13}/><button><Trash2 size={14}/></button></div><p>Write a concise explanation of how transformer models work.</p></div><button className="add-message"><Plus size={14}/> Add message</button><div className="parameter-header"><label>Parameters</label><button className="reset">Reset</button></div><div className="parameters"><div><span>Temperature</span><strong>0.7</strong></div><input type="range" defaultValue="70"/><div><span>Max tokens</span><strong>1024</strong></div><input type="range" defaultValue="45"/></div></div> : tab === "Response" ? <Response /> : <CodePanel />}</Card><Card className="panel response-panel"><div className="response-head"><div><label>Response</label><Status>200 OK</Status></div><span className="latency"><Timer size={13}/> 842ms</span></div><div className="response-content"><div className="response-placeholder"><Check size={18}/><span>Run the request to see the response</span><small>Your response will appear here</small></div></div><div className="response-foot"><span>Tokens <strong>— / —</strong></span><span>Model <strong>veyra-core-70b</strong></span></div></Card></div></> }
function Response() { return <div className="code-area"><pre>{`{\n  "id": "chatcmpl_7x92k",\n  "object": "chat.completion",\n  "model": "veyra-core-70b",\n  "choices": [\n    {\n      "index": 0,\n      "message": {\n        "role": "assistant",\n        "content": "A transformer is a neural network architecture..."\n      },\n      "finish_reason": "stop"\n    }\n  ]\n}`}</pre><CopyButton/></div> }
function CodePanel() { return <div className="code-panel"><div className="code-tabs"><span className="code-active">cURL</span><span>JavaScript</span><span>Python</span><CopyButton/></div><div className="code-area"><pre>{`curl https://api.veyra.ai/v1/chat/completions \\\n  -H "Authorization: Bearer $VEYRA_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{
    "model": "veyra-core-70b",
    "messages": [{ "role": "user", "content": "Hello" }]
  }'`}</pre></div></div> }

function ApiView() { const keys = [{name:"Production key", value:"vra_live_••••••••••••8f2a", created:"Today", last:"Just now"},{name:"Development key", value:"vra_test_••••••••••••3c91", created:"Aug 24, 2024", last:"2 hours ago"}]; return <><PageHeader eyebrow="DEVELOP / API" title="API" description="Everything you need to integrate Veyra into your application." action={<button className="button primary"><Plus size={15}/> Create API key</button>}/><div className="metric-strip"><div><span>API status</span><strong><i className="live-dot"/> Operational</strong></div><div><span>Requests this month</span><strong>24,892</strong></div><div><span>Current plan</span><strong>Developer <ArrowUpRight size={14}/></strong></div></div><section className="section"><div className="section-heading"><div><h2>API keys</h2><p>Keys authenticate requests to the Veyra API. Keep them secure.</p></div><button className="button secondary"><KeyRound size={15}/> Documentation</button></div><Card><div className="table"><div className="table-head key-grid"><span>Name</span><span>Key</span><span>Created</span><span>Last used</span><span/></div>{keys.map(key => <div className="table-row key-grid" key={key.name}><div className="key-name"><div className="key-icon"><KeyRound size={14}/></div><strong>{key.name}</strong></div><code>{key.value}</code><span>{key.created}</span><span>{key.last}</span><button className="row-menu"><MoreHorizontal size={16}/></button></div>)}</div></Card></section><section className="section"><div className="section-heading"><div><h2>Endpoints</h2><p>Available API endpoints and their current status.</p></div></div><Card><div className="table"><div className="table-head endpoint-grid"><span>Method</span><span>Endpoint</span><span>Description</span><span>Status</span></div>{[["POST","/v1/chat/completions","Generate a model response"],["GET","/v1/models","List available models"],["GET","/v1/usage","View usage statistics"],["GET","/v1/health","Check API health"]].map(row => <div className="table-row endpoint-grid" key={row[1]}><span className={`method-badge ${row[0].toLowerCase()}`}>{row[0]}</span><code>{row[1]}</code><span>{row[2]}</span><Status>Operational</Status></div>)}</div></Card></section></> }

function ModelsView() { return <><PageHeader eyebrow="DEVELOP / MODELS" title="Models" description="Explore Veyra's model lineup and find the right fit for your workload." action={<button className="button secondary"><BookOpen size={15}/> Model docs</button>}/><div className="filter-row"><div className="search-input"><Search size={15}/><input placeholder="Filter models..."/></div><button className="filter-button">All models <ChevronDown size={14}/></button></div><Card><div className="table"><div className="table-head models-grid"><span>Model</span><span>Type</span><span>Context window</span><span>Speed</span><span>Status</span></div>{models.map(model => <div className="table-row models-grid" key={model.id}><div className="model-name"><div className="model-glyph"><Bot size={15}/></div><div><strong>{model.name}</strong><code>{model.id}</code></div></div><span>{model.type}</span><span>{model.context} tokens</span><span>{model.speed}</span><Status tone={model.status === "Beta" ? "blue" : "green"}>{model.status}</Status></div>)}</div></Card></> }

const docsContent: Record<string, {section: string; read: string; intro: string; blocks: {title: string; body: string; code?: string}[]}> = {
  Introduction: {section: "GETTING STARTED", read: "4 min read", intro: "Build intelligent applications with Veyra's fast, reliable language models.", blocks: [{title: "Build with Veyra", body: "Veyra gives developers simple, production-ready access to powerful AI models. Make your first request in minutes with our intuitive API."}, {title: "What you can build", body: "Create chat assistants, coding tools, content workflows, and production automations with the same OpenAI-compatible request shape."}]},
  Quickstart: {section: "GETTING STARTED", read: "6 min read", intro: "Send your first model request from a local project.", blocks: [{title: "Install the SDK", body: "Use the official client in a TypeScript project.", code: "npm install @veyra-ai/sdk"}, {title: "Create a request", body: "Keep your API key on the server and send a messages array to the chat completions endpoint.", code: `import { Veyra } from \"@veyra-ai/sdk\";\n\nconst veyra = new Veyra({ apiKey: process.env.VEYRA_API_KEY });\nconst result = await veyra.chat.completions.create({\n  model: \"veyra-core-70b\",\n  messages: [{ role: \"user\", content: \"Hello, Veyra\" }]\n});`}]},
  Authentication: {section: "GETTING STARTED", read: "3 min read", intro: "Authenticate every API request with a workspace key.", blocks: [{title: "Bearer authentication", body: "Send the key in the Authorization header. Never expose production keys in browser code or commit them to source control.", code: `curl https://api.veyra.ai/v1/models \\\n  -H \"Authorization: Bearer $VEYRA_API_KEY\"`}, {title: "Key safety", body: "Use separate development and production keys, rotate them regularly, and store them in your deployment environment."}]},
  "First Request": {section: "GETTING STARTED", read: "4 min read", intro: "Understand the smallest valid chat completion request.", blocks: [{title: "Required fields", body: "Every request includes a model identifier and at least one message with a role and content."}, {title: "Response shape", body: "Read the generated text from choices[0].message.content and inspect usage for token counts."}]},
  "Chat Completions": {section: "API", read: "8 min read", intro: "Generate conversational responses with Veyra models.", blocks: [{title: "Endpoint", body: "POST /v1/chat/completions accepts messages, model, temperature, max_tokens, and streaming options."}, {title: "Streaming", body: "Set stream to true to receive incremental data-only server-sent events as the model generates a response."}]},
  Models: {section: "API", read: "5 min read", intro: "Choose a model based on capability, context, and speed.", blocks: [{title: "Available models", body: "Veyra Core 70B is the general-purpose default. Swift 8B prioritizes latency, Reason 32B handles complex reasoning, and Vision supports multimodal input."}]},
  "API Keys": {section: "API", read: "4 min read", intro: "Create, rotate, and secure keys for your workspace.", blocks: [{title: "Key types", body: "Development keys are intended for local testing. Production keys should be restricted to deployed services and rotated after team changes."}]},
  Usage: {section: "API", read: "4 min read", intro: "Monitor request volume and token consumption.", blocks: [{title: "Usage metrics", body: "The usage endpoint returns request counts, input tokens, output tokens, and daily aggregates for your workspace."}]},
  Health: {section: "API", read: "2 min read", intro: "Check service availability before sending work.", blocks: [{title: "Health endpoint", body: "GET /v1/health returns a lightweight operational status for the API gateway and model service."}]},
  Errors: {section: "API", read: "6 min read", intro: "Handle validation, authentication, rate limit, and server errors.", blocks: [{title: "Error format", body: "Errors include a stable type, message, and request_id. Use request_id when contacting support or debugging logs."}]},
  "Using Veyra": {section: "GUIDES", read: "7 min read", intro: "Patterns for building a reliable Veyra integration.", blocks: [{title: "Production checklist", body: "Set timeouts, retry only safe failures, log request IDs, and stream long responses to improve perceived latency."}]},
  Playground: {section: "GUIDES", read: "3 min read", intro: "Iterate on prompts interactively before writing integration code.", blocks: [{title: "Try a request", body: "Open Playground, edit the request message, choose a model, then run it. Use the Code tab to copy a ready-to-use example."}]},
  "API Errors": {section: "GUIDES", read: "6 min read", intro: "Diagnose common API failures quickly.", blocks: [{title: "Debugging flow", body: "Confirm the endpoint, authorization header, model ID, and JSON shape. Then check API Health and the request ID."}]},
  Streaming: {section: "GUIDES", read: "8 min read", intro: "Deliver generated text as it becomes available.", blocks: [{title: "Server-sent events", body: "Consume data chunks until the stream sends [DONE]. Accumulate delta.content values to render the final response."}]},
  "API Reference": {section: "REFERENCE", read: "10 min read", intro: "A complete overview of Veyra HTTP resources.", blocks: [{title: "Resources", body: "Use /v1/chat/completions for generation, /v1/models for discovery, /v1/usage for metrics, and /v1/health for status."}]},
  Responses: {section: "REFERENCE", read: "5 min read", intro: "Interpret completion responses and usage metadata.", blocks: [{title: "Completion object", body: "Responses include an ID, model, choices, finish reason, and usage totals. Persist the ID when you need traceability."}]},
}

function DocsView2() {
  const [doc, setDoc] = useState("Introduction")
  const [query, setQuery] = useState("")
  const content = docsContent[doc] ?? docsContent.Introduction
  const groups = [["GETTING STARTED", ["Introduction", "Quickstart", "Authentication", "First Request"]], ["API", ["Chat Completions", "Models", "API Keys", "Usage", "Health", "Errors"]], ["GUIDES", ["Using Veyra", "Playground", "API Errors", "Streaming"]], ["REFERENCE", ["API Reference", "Responses"]]] as const
  return <div className="docs-layout"><aside className="docs-nav"><label className="docs-search"><Search size={14}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search docs..."/><kbd>⌘ K</kbd></label>{groups.map(([group, items]) => <div className="docs-group" key={group}><label>{group}</label>{items.filter(item => !query.trim() || item.toLowerCase().includes(query.toLowerCase())).map(item => <button key={item} className={doc === item ? "doc-link active" : "doc-link"} onClick={() => setDoc(item)}>{item}</button>)}</div>)}</aside><article className="doc-article"><div className="eyebrow">{content.section}</div><h1>{doc}</h1><p className="lead">{content.intro}</p><div className="doc-updated">Last updated Sep 19, 2026 <span>·</span> {content.read}</div>{content.blocks.map((block, index) => <section key={block.title}><h2>{block.title}</h2><p>{block.body}</p>{block.code && <div className="doc-code"><div><span>Example</span><CopyButton/></div><pre>{block.code}</pre></div>}{index === 0 && <div className="callout"><Zap size={17}/><div><strong>Tip</strong><p>Try this flow in the Playground, then use the Code tab to copy the request.</p></div></div>}</section>)}</article><aside className="on-page"><label>ON THIS PAGE</label>{content.blocks.map(block => <a href={`#${block.title.toLowerCase().replaceAll(" ", "-")}`} key={block.title}>{block.title}</a>)}</aside></div>
}

function DocsView() { const [doc, setDoc] = useState("Introduction"); return <div className="docs-layout"><aside className="docs-nav"><div className="docs-search"><Search size={14}/> Search docs <kbd>⌘ K</kbd></div>{[["GETTING STARTED",["Introduction","Quickstart","Authentication","First Request"]],["API",["Chat Completions","Models","API Keys","Usage","Health","Errors"]],["GUIDES",["Using Veyra","Playground","API Errors","Streaming"]],["REFERENCE",["API Reference","Responses"]]].map(([group,items]) => <div className="docs-group" key={group as string}><label>{group as string}</label>{(items as string[]).map(item => <button key={item} className={doc === item ? "doc-link active" : "doc-link"} onClick={() => setDoc(item)}>{item}</button>)}</div>)}</aside><article className="doc-article"><div className="eyebrow">GETTING STARTED</div><h1>{doc}</h1><p className="lead">Build intelligent applications with Veyra&apos;s fast, reliable language models.</p><div className="doc-updated">Last updated Sep 12, 2024 <span>·</span> 4 min read</div><h2>Build with Veyra</h2><p>Veyra gives developers simple, production-ready access to powerful AI models. Make your first request in minutes with our intuitive API.</p><div className="callout"><Zap size={17}/><div><strong>New: Veyra Reason</strong><p>Our reasoning model is now available in beta. <u>Try it in the Playground →</u></p></div></div><h2>Make your first request</h2><p>Use your API key to authenticate requests. Here&apos;s a minimal example:</p><div className="doc-code"><div><span>cURL</span><CopyButton/></div><pre>{`curl https://api.veyra.ai/v1/chat/completions \\\n  -H "Authorization: Bearer $VEYRA_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"model":"veyra-core-70b","messages":[{"role":"user","content":"Hello, Veyra"}]}'`}</pre></div><h2>What&apos;s next</h2><p>Explore the <u>Playground</u> to iterate on prompts, or read about <u>streaming responses</u> for production applications.</p></article><aside className="on-page"><label>ON THIS PAGE</label><a className="current">Build with Veyra</a><a>Make your first request</a><a>What&apos;s next</a><div className="feedback"><span>Was this helpful?</span><button>Yes</button><button>No</button></div></aside></div> }

function UsageView() { return <><PageHeader eyebrow="MONITOR / USAGE" title="Usage" description="Track requests, tokens, and spend across your workspace." action={<button className="button secondary">Last 30 days <ChevronDown size={14}/></button>}/><div className="usage-metrics"><Card><span>Total requests</span><strong>24,892</strong><small className="positive">↑ 18.2% <em>vs. previous period</em></small></Card><Card><span>Tokens processed</span><strong>8.4M</strong><small className="positive">↑ 12.6% <em>vs. previous period</em></small></Card><Card><span>Estimated spend</span><strong>$42.18</strong><small>Developer plan <em>resets in 12 days</em></small></Card></div><Card className="chart-card"><div className="chart-heading"><div><h2>Requests</h2><p>Daily request volume</p></div><div className="legend"><i/> Requests <i className="orange"/> Tokens</div></div><div className="chart"><div className="chart-y"><span>2k</span><span>1.5k</span><span>1k</span><span>500</span><span>0</span></div><div className="chart-lines"><div/><div/><div/><div/><div/><svg viewBox="0 0 700 170" preserveAspectRatio="none"><path d="M0 138 C35 132, 40 105, 72 116 S115 132, 140 98 S182 110, 215 88 S260 105, 292 70 S336 93, 370 62 S410 76, 445 54 S484 68, 520 42 S560 66, 600 31 S655 49, 700 20"/><path className="line-orange" d="M0 156 C45 150, 72 144, 100 149 S165 132, 200 140 S250 119, 288 127 S344 113, 380 119 S430 96, 470 108 S520 88, 558 96 S620 72, 700 70"/></svg><div className="chart-x"><span>Sep 1</span><span>Sep 8</span><span>Sep 15</span><span>Sep 22</span><span>Sep 29</span></div></div></div></Card></> }
function HealthView() { return <><PageHeader eyebrow="MONITOR / API HEALTH" title="API health" description="Real-time status and performance for Veyra services." action={<span className="status large"><i/> All systems operational</span>}/><div className="health-summary"><div className="health-mark"><Check size={25}/></div><div><h2>Everything is operational</h2><p>All Veyra systems are running normally.</p></div><span>Updated just now</span></div><div className="health-grid">{[["Model service","Operational","99.99%","48ms"],["API gateway","Operational","100%","12ms"],["Embeddings","Operational","99.98%","84ms"],["Dashboard","Operational","100%","—"]].map(item => <Card key={item[0]}><div className="health-card-head"><span className="health-icon"><Activity size={16}/></span><Status>{item[1]}</Status></div><h3>{item[0]}</h3><div className="health-values"><span><small>Uptime</small><strong>{item[2]}</strong></span><span><small>Latency</small><strong>{item[3]}</strong></span></div></Card>)}</div></> }
function SettingsView() { return <><PageHeader eyebrow="SYSTEM / SETTINGS" title="Settings" description="Manage your workspace and developer preferences."/><div className="settings-layout"><aside className="settings-nav"><button className="active">General</button><button>Workspace</button><button>Members</button><button>Billing</button><button>Danger zone</button></aside><Card className="settings-content"><div className="settings-section"><h2>General</h2><p>Update your workspace details and preferences.</p><label>Workspace name<input defaultValue="Acme workspace"/></label><label>Workspace slug<div className="input-prefix"><span>veyra.ai/</span><input defaultValue="acme"/></div></label><button className="button primary">Save changes</button></div><div className="settings-section"><h2>Appearance</h2><p>Customize how Veyra looks for you.</p><div className="theme-options"><button className="selected"><div className="light-preview"/>Light <Check size={14}/></button><button><div className="dark-preview"/>Dark</button><button><div className="system-preview"/>System</button></div></div></Card></div></> }

function CommandPalette({ close, navigate }: {close: () => void, navigate: (v: View) => void}) { const commands = ["Chat","Playground","API","Models","Docs","Usage","API Health","Settings"] as View[]; return <div className="command-overlay" onClick={close}><div className="command-palette" onClick={e => e.stopPropagation()}><div className="command-search"><Search size={17}/><input autoFocus placeholder="Search pages, docs, and actions..."/><kbd>ESC</kbd></div><div className="command-list"><label>QUICK NAVIGATION</label>{commands.map((c, i) => <button key={c} onClick={() => navigate(c)}><span className="command-icon">{i < 2 ? <MessageSquare size={15}/> : <Command size={15}/>}</span>{c}<kbd>{i < 3 ? `⌘ ${i + 1}` : ""}</kbd></button>)}</div><div className="command-foot"><span><ArrowUpRight size={13}/> Open</span><span><span className="arrow-keys">↑ ↓</span> Navigate</span><span><kbd>ESC</kbd> Close</span></div></div></div> }
